### ISSUE TITLE
can't find the file

### ISSUE THREAD

**Issue by glbydl** [ContinuumIO/nutchpy#22]
Hi
    I already downloaded the nutchpy, and try to execute the example.
    But it came up with an error like "FileNotFoundError: [WinError 2] The system cannot find the file specified"
    My operation system is Windows 10 and the full console information shows as below.

    Traceback (most recent call last):
  File "C:\cygwin64\home\nutchpy\test.py", line 1, in <module>
    import nutchpy
  File "C:\cygwin64\home\nutchpy\nutchpy\__init__.py", line 6, in <module>
    from .JVM import gateway
  File "C:\cygwin64\home\nutchpy\nutchpy\JVM.py", line 91, in <module>
    gateway = NutchJavaGateway().gateway
  File "C:\cygwin64\home\nutchpy\nutchpy\JVM.py", line 88, in gateway
    self._gateway = launch_gateway()
  File "C:\cygwin64\home\nutchpy\nutchpy\JVM.py", line 38, in launch_gateway
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python35-32\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Python35-32\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] FileNotFoundError: [WinError 2] The system cannot find the file specified

    So I don't know how to fix it and also I have no idea the what file the system is looking for. I am very sure the path of crawling result data is correct.

Thank you.

**Comment by chrismattmann** [comment]
Hi @glbydl what version of Python are you using? Also did you first start the Nutch gateway?

**Comment by glbydl** [comment]
Hi professor, the vsersion of Python I am using is 3.5. And sorry may I ask what do you mean by "start the Nutch gateway"?
