### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space | SequenceReader.read

### ISSUE THREAD

**Issue by karanjeets** [ContinuumIO/nutchpy#25]
I am getting the below error while parsing data file in crawldb. Please note that the size of file is 136 MB and it has lot of URLs in it. 

As far as I am able to understand, SequenceReader.read tries to put all extracted data into java heap and then processes it. Therefore it works for small inputs (considering my allotted heap space) and fail for large ones.

**Question - Is it possible to process the data in incremental fashion (in parts) and release the memory as you go on ? May be StreamingSequenceReader.read ?**

===
***Error Details***
Traceback (most recent call last):
  File "get_domains.py", line 41, in <module>
    main(sys.argv[1])
  File "get_domains.py", line 18, in main
    parse_data = nutchpy.sequence_reader.read(data)
  File "/root/anaconda/lib/python2.7/site-packages/nutchpy/readers.py", line 113, in read
    data = self.reader.read(path)
  File "/root/anaconda/lib/python2.7/site-packages/py4j/java_gateway.py", line 538, in __call__
    self.target_id, self.name)
  File "/root/anaconda/lib/python2.7/site-packages/py4j/protocol.py", line 300, in get_return_value
    format(target_id, '.', name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.continuumio.seqreaderapp.SequenceReader.read.
: java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
        at java.lang.StringBuilder.append(StringBuilder.java:136)
        at org.apache.nutch.crawl.CrawlDatum.toString(CrawlDatum.java:409)
        at com.continuumio.seqreaderapp.SequenceReader.read(SequenceReader.java:113)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:207)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Pramodnagarajarao** [comment]
I am getting the same error if I try to read the entire file at once. If being read in chunks (Say few rows of data), I can read the data. Any pointers on how to resolve the issue? 

Error as seen in the log window: I have miniconda3 installed with Python 3.4

py4j.protocol.Py4JJavaError: An error occurred while calling z:com.continuumio.seqreaderapp.SequenceReader.head.
: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:89)
	at org.apache.nutch.crawl.CrawlDatum.toString(CrawlDatum.java:408)
	at com.continuumio.seqreaderapp.SequenceReader.head(SequenceReader.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)

**Comment by karanjeets** [comment]
Hi @Pramodnagarajarao 
As a work around may be you can create a script to read over segments (instead of one crawldb data file) iteratively.

**Comment by Pramodnagarajarao** [comment]
Thanks @karanjeets. 
You mean to say that we need to read from segment directory's associated data file and not crawldb data file with sequence_reader.read() methods intact? If yes, I have tried that too. Didn't succeed.

**Comment by thammegowda** [comment]
@karanjeets @Pramodnagarajarao 

Theres is a better way, using stream/iterator reader: [example](https://github.com/ContinuumIO/nutchpy/blob/master/examples/seq_reader.py#L32)
