### ISSUE TITLE
Version upgrade

### ISSUE THREAD

**Issue by TaichiHo** [ContinuumIO/nutchpy#26]
I got some problem reading the data I crawled. The trace is as following. I checked out the newest version in nutch, and it is already 8 instead of 7. Might be a good time to upgrade the dependency version.
```
Traceback (most recent call last):
  File "readStatistics.py", line 96, in <module>
    main()
  File "readStatistics.py", line 19, in main
    count = nutchpy.sequence_reader.count(crawlDbFile)
  File "/Users/Taichi1/miniconda3/lib/python3.4/site-packages/nutchpy/readers.py", line 173, in count
    count = self.reader.count(path)
  File "/Users/Taichi1/miniconda3/lib/python3.4/site-packages/py4j/java_gateway.py", line 813, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Users/Taichi1/miniconda3/lib/python3.4/site-packages/py4j/protocol.py", line 308, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.continuumio.seqreaderapp.SequenceReader.count.
: A record version mismatch occured. Expecting v7, found v8
	at org.apache.nutch.crawl.CrawlDatum.readFields(CrawlDatum.java:246)
	at org.apache.hadoop.io.SequenceFile$Reader.getCurrentValue(SequenceFile.java:1751)
	at org.apache.hadoop.io.SequenceFile$Reader.next(SequenceFile.java:1879)
	at com.continuumio.seqreaderapp.SequenceReader.count(SequenceReader.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ayberk** [comment]
Have you tried the suggestion in the wiki? 

https://github.com/ContinuumIO/nutchpy/wiki#troubleshoot

**Comment by TaichiHo** [comment]
The problem seems to be the protocol-status update in nutch: https://issues.apache.org/jira/browse/NUTCH-2129

This patch upgrades the crawlDatum class and makes it version 8, while the dependency in nutchpy only accepts version 7.

**Comment by chrismattmann** [comment]
moving to REST architecture here.
